<?xml version="1.0"?>
<package format="3">
  <name>realsense_depth_pub</name>
  <version>0.0.1</version>
  <description>Publish depth camera images for the BXI controller.</description>
  <maintainer email="you@example.com">you</maintainer>
  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>

  <exec_depend>orbbec_camera</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <test_depend>ament_cmake_pytest</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
