sources:
  #手柄按键配置
  gamepad:
    type: joystick
    device: /dev/input/js0
    signals:
      #ps4
      # gamepad.left_y: {from: js.axis.4, timeout_ms: 3000, failsafe: 0.0}
      # gamepad.left_x: {from: js.axis.0, timeout_ms: 3000, failsafe: 0.0}
      # gamepad.yaw: {from: js.axis.6, timeout_ms: 3000, failsafe: 0.0}
      # gamepad.trigger_left: {from: js.axis.2}
      # gamepad.trigger_right: {from: js.axis.5}
      # gamepad.stop: {from: js.button.9}
      # gamepad.start: {from: js.button.10}
      # gamepad.lb: {from: js.button.4}
      # gamepad.rb: {from: js.button.5}
      # gamepad.a: {from: js.button.0}
      # gamepad.b: {from: js.button.1}
      # gamepad.x: {from: js.button.2}
      # gamepad.y: {from: js.button.3}
      #xbox
      gamepad.left_y: {from: js.axis.3, timeout_ms: 3000, failsafe: 0.0}
      gamepad.left_x: {from: js.axis.0, timeout_ms: 3000, failsafe: 0.0}
      gamepad.yaw: {from: js.axis.6, timeout_ms: 3000, failsafe: 0.0}
      gamepad.trigger_left: {from: js.axis.5}
      gamepad.trigger_right: {from: js.axis.4}
      gamepad.stop: {from: js.button.11}
      gamepad.start: {from: js.button.14}
      gamepad.lb: {from: js.button.6}
      gamepad.rb: {from: js.button.7}
      gamepad.a: {from: js.button.0}
      gamepad.b: {from: js.button.1}
      gamepad.x: {from: js.button.3}
      gamepad.y: {from: js.button.4}

  #键盘按键配置
  keyboard:
    type: keyboard
    poll_timeout_us: 20000
    hold_ms: 200
    stop: space
    signals:
      keyboard.vx: {from: keyboard.axis, negative: s, positive: w}
      keyboard.vy: {from: keyboard.axis, negative: d, positive: a}
      keyboard.yaw: {from: keyboard.axis, negative: e, positive: q}
      keyboard.normal: {from: keyboard.key, key: "1", hold_ms: 200}
      keyboard.recover: {from: keyboard.key, key: "2"}
      keyboard.dance: {from: keyboard.key, key: "3"}
      keyboard.amp_run: {from: keyboard.key, key: "4"}
      keyboard.normal_run: {from: keyboard.key, key: "5"}
      keyboard.back_flip: {from: keyboard.key, key: "6"}
      keyboard.forward_flip: {from: keyboard.key, key: "7"}
      keyboard.applause: {from: keyboard.key, key: "8"}
      keyboard.hello: {from: keyboard.key, key: "9"}

#预设的一些，输入曲线
curves:
  stick:
    type: expo
    deadzone: 0.03
    expo: 0.0
    limit: [-1.0, 1.0]
    calibration:
      input: [-1.0, 0.0, 1.0]
      output: [-1.0, 0.0, 1.0]

#处理来自不同source的输入，映射到统一的controls
controls:
  move.vx:
    type: analog
    mix: max_abs
    sources:
      - source: gamepad.left_y
        direction: -1
        curve: stick
      - source: keyboard.vx
    deadzone: 0.03
    min: -1.0
    max: 1.0
    alpha: 0.03

  move.vy:
    type: analog
    mix: max_abs
    sources:
      - source: gamepad.left_x
        direction: -1
        curve: stick
      - source: keyboard.vy
    deadzone: 0.03
    min: -1.0
    max: 1.0
    alpha: 0.03

  move.yaw:
    type: analog
    mix: max_abs
    sources:
      - source: gamepad.yaw
        direction: -1
        curve: stick
      - source: keyboard.yaw
    deadzone: 0.03
    min: -1.0
    max: 1.0
    alpha: 0.05

  system.stop_event: {type: bool, source: gamepad.stop}
  system.start_event: {type: bool, source: gamepad.start}
  shoulder.left_event: {type: bool, source: gamepad.lb}
  shoulder.right_event: {type: bool, source: gamepad.rb}
  button.a_event: {type: bool, source: gamepad.a}
  button.b_event: {type: bool, source: gamepad.b}
  button.x_event: {type: bool, source: gamepad.x}
  button.y_event: {type: bool, source: gamepad.y}

  trigger.left_event:
    type: bool
    source: gamepad.trigger_left
    threshold: 0.85
    hysteresis: 0.05

  trigger.right_event:
    type: bool
    source: gamepad.trigger_right
    threshold: 0.85
    hysteresis: 0.05

  keyboard.normal_event: {type: bool, source: keyboard.normal}
  keyboard.recover_event: {type: bool, source: keyboard.recover}
  keyboard.dance_event: {type: bool, source: keyboard.dance}
  keyboard.amp_run_event: {type: bool, source: keyboard.amp_run}
  keyboard.normal_run_event: {type: bool, source: keyboard.normal_run}
  keyboard.back_flip_event: {type: bool, source: keyboard.back_flip}
  keyboard.forward_flip_event: {type: bool, source: keyboard.forward_flip}
  keyboard.applause_event: {type: bool, source: keyboard.applause}
  keyboard.hello_event: {type: bool, source: keyboard.hello}

#将统一的controls映射到输出
outputs:
  conflict_policy: first_wins
  publish_on_change: true

  #连续的模拟值
  analog:
    vx: move.vx
    vy: move.vy
    yaw: move.yaw

  #上升沿触发，满足条件会输出目标值随后恢复为0
  edge:
    #sysyem.<name>代表触发下面的特定命令
    - output: system.stop
      when: [system.stop_event]
    - output: system.start
      when: [system.start_event]

  #电平触发，满足条件会一直输出
  level:
    - output: btn_1=1
      when:
        any:
          - [shoulder.right_event, button.x_event]
          - [keyboard.normal_event]

    - output: btn_2=1
      when: [shoulder.right_event, button.a_event]

    - output: btn_3=1
      when: [shoulder.right_event, button.b_event]

    - output: btn_4=1
      when: [shoulder.right_event, button.y_event]

    - output: btn_5=1
      when:
        any:
          - [shoulder.left_event, button.x_event]
          - [keyboard.dance_event]

    - output: btn_6=1
      when:
        any:
          - [shoulder.left_event, button.a_event]
          - [keyboard.recover_event]

    - output: btn_7=1
      when:
        any:
          - [shoulder.left_event, button.b_event]
          - [keyboard.normal_run_event]

    - output: btn_8=1
      when:
        any:
          - [shoulder.left_event, button.y_event]
          - [keyboard.amp_run_event]

    - output: btn_9=1
      when:
        - button.x_event
        - released: shoulder.left_event
        - released: shoulder.right_event
        - released: trigger.left_event
        - released: trigger.right_event

    - output: btn_10=1
      when:
        any:
          - [trigger.left_event, button.x_event]
          - [keyboard.back_flip_event]

    - output: btn_10=2
      when:
        any:
          - [trigger.left_event, button.y_event]
          - [keyboard.forward_flip_event]

    - output: btn_10=3
      when:
        any:
          - [trigger.left_event, button.a_event]

    - output: btn_10=4
      when:
        any:
          - [trigger.left_event, button.b_event]

    - output: btn_10=5
      when:
        any:
          - [trigger.right_event, button.b_event]
          - [keyboard.applause_event]

    - output: btn_10=6
      when:
        any:
          - [trigger.right_event, button.a_event]
          - [keyboard.hello_event]

#自定义命令
system:
  start:
    - "mkdir -p /var/log/bxi_log"
    - "ros2 launch bxi_example_py_elf3 example_demo_hw.launch.py > /var/log/bxi_log/$(date +%Y-%m-%d_%H-%M-%S)_elf.log 2>&1 &"
    - "ros2 launch bxi_example_bms bms.launch.py > /var/log/bxi_log/bms_$(date +%Y-%m-%d_%H-%M-%S)_bms.log 2>&1 &"
    - "su bxi -c \"cd /home/bxi/bxi_ws/bxi_voice && ./bin/bxi-voice\" 2>&1 &"
  stop:
    - "killall -SIGINT hardware_elf3"
    - "killall -SIGINT hardware_elf3_neck"
    - "killall -SIGINT bxi_example_py_elf3"
    - "killall -SIGINT bxi_example_py_elf3_demo"
    - "killall -SIGINT bxi_bms"
    - "killall -SIGINT bxi_example_bms"
    - "killall -SIGINT bxi-voice"

#互斥定义，只能acquire一次，但是可以release多次
system_mutexes:
  robot_process:
    acquire: start
    release: stop

#重置摇杆的滤波器
system_reset_motion_after:
  - start
  - stop
