import os
from typing import Any


DEFAULT_ROBOT_CONFIG_FILE = "/opt/bxi/robot_config.yaml"
DEFAULT_HARDWARE_CONFIG = {
    "hardware_config/imu": True,
    "hardware_config/motor_pwr": True,
    "hardware_config/motor_disable": 0x60000000,
}
HEAD_MOTOR_DISABLE_MASK = 0x60000000


def declare_hardware_launch_arguments() -> list[Any]:
    from launch.actions import DeclareLaunchArgument

    default_config_file = os.environ.get(
        "BXI_ROBOT_CONFIG_FILE",
        DEFAULT_ROBOT_CONFIG_FILE,
    )
    return [
        DeclareLaunchArgument(
            "robot_config_file",
            default_value=default_config_file,
            description="Robot hardware config YAML generated by bxi_robot_config_tool.",
        ),
        DeclareLaunchArgument(
            "enable_head",
            default_value="auto",
            description="Use true/false to override modules.head.enabled, or auto.",
        ),
    ]


def hardware_node_from_context(
    context,
    *,
    disable_imu: bool = False,
    imu_topic: str | None = None,
) -> Any:
    from launch.substitutions import LaunchConfiguration
    from launch_ros.actions import Node

    config_file = LaunchConfiguration("robot_config_file").perform(context)
    enable_head_arg = LaunchConfiguration("enable_head").perform(context)
    robot_config = _load_robot_config(config_file)
    enable_head = _resolve_enable_head(enable_head_arg, robot_config)
    hardware_config = _resolve_hardware_config(robot_config, enable_head)
    if disable_imu:
        # The standalone hipnuc_imu node owns hardware/imu_data in this mode.
        hardware_config["hardware_config/imu"] = False
    package_name = "hardware_elf3"

    print(
        "[bxi hardware config] "
        f"package={package_name}, "
        f"motor_disable=0x{hardware_config['hardware_config/motor_disable']:08X}, "
        f"config_file={config_file or '<none>'}"
    )

    remappings = []
    if imu_topic:
        remappings.append(("hardware/imu_data", imu_topic))

    return Node(
        package=package_name,
        executable=package_name,
        name=package_name,
        output="screen",
        parameters=[hardware_config],
        remappings=remappings,
        emulate_tty=True,
        arguments=[("__log_level:=debug")],
    )


def _load_robot_config(config_file: str) -> dict[str, Any]:
    if not config_file:
        return {}

    path = os.path.expandvars(os.path.expanduser(config_file))
    if not os.path.exists(path):
        print(
            f"[bxi hardware config] {path} not found, using built-in defaults."
        )
        return {}

    try:
        import yaml

        with open(path, "r", encoding="utf-8") as config:
            data = yaml.safe_load(config) or {}
    except Exception as exc:
        print(
            f"[bxi hardware config] cannot read {path}: {exc}; "
            "using built-in defaults."
        )
        return {}

    if not isinstance(data, dict):
        print(
            f"[bxi hardware config] {path} root is not a map, using built-in defaults."
        )
        return {}
    return data


def _resolve_enable_head(enable_head_arg: str, robot_config: dict[str, Any]) -> bool:
    mode = str(enable_head_arg or "auto").strip().lower()
    if mode == "auto":
        configured = _head_enabled_from_config(robot_config)
        return bool(configured) if configured is not None else False
    parsed = _parse_bool(mode)
    if parsed is None:
        print(
            f"[bxi hardware config] invalid enable_head={enable_head_arg!r}, "
            "using auto."
        )
        configured = _head_enabled_from_config(robot_config)
        return bool(configured) if configured is not None else False
    return parsed


def _head_enabled_from_config(robot_config: dict[str, Any]) -> bool | None:
    modules = robot_config.get("modules", {})
    if not isinstance(modules, dict):
        return None
    head = modules.get("head", {})
    if not isinstance(head, dict) or "enabled" not in head:
        return None
    enabled = head.get("enabled")
    parsed = _parse_bool(enabled)
    return parsed if parsed is not None else bool(enabled)


def _resolve_hardware_config(
    robot_config: dict[str, Any],
    enable_head: bool,
) -> dict[str, Any]:
    hardware_config = dict(DEFAULT_HARDWARE_CONFIG)
    hardware_config.update(_hardware_config_from_robot_config(robot_config))

    motor_disable = int(hardware_config["hardware_config/motor_disable"])
    if enable_head:
        motor_disable &= ~HEAD_MOTOR_DISABLE_MASK
    else:
        motor_disable |= HEAD_MOTOR_DISABLE_MASK
    hardware_config["hardware_config/motor_disable"] = motor_disable
    return hardware_config


def _hardware_config_from_robot_config(robot_config: dict[str, Any]) -> dict[str, Any]:
    hardware_config = robot_config.get("hardware_config", {})
    if not isinstance(hardware_config, dict):
        return {}

    values: dict[str, Any] = {}
    for key, value in hardware_config.items():
        parameter_name = key if "/" in key else f"hardware_config/{key}"
        if parameter_name.endswith("/motor_disable"):
            values[parameter_name] = _parse_int(
                value,
                DEFAULT_HARDWARE_CONFIG[parameter_name],
            )
        else:
            parsed_bool = _parse_bool(value)
            values[parameter_name] = parsed_bool if parsed_bool is not None else value
    return values


def _parse_bool(value: Any) -> bool | None:
    if isinstance(value, bool):
        return value
    text = str(value).strip().lower()
    if text in ("1", "true", "yes", "on"):
        return True
    if text in ("0", "false", "no", "off"):
        return False
    return None


def _parse_int(value: Any, default: int) -> int:
    try:
        if isinstance(value, str):
            return int(value.strip(), 0)
        return int(value)
    except (TypeError, ValueError):
        print(
            f"[bxi hardware config] invalid motor_disable={value!r}, "
            f"using 0x{default:08X}."
        )
        return default
